# Generated by Django 5.2.9 on 2026-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_part1', models.CharField(max_length=50, verbose_name='Ism 1-qism')),
                ('name_part2', models.CharField(max_length=50, verbose_name='Ism 2-qism')),
                ('name_part3', models.CharField(max_length=50, verbose_name='Ism 3-qism')),
                ('bio_title', models.TextField(verbose_name='Bio title')),
                ('bio_content', models.TextField(verbose_name='Bio content')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m', verbose_name='Photo')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
