# Generated by Django 5.2.9 on 2026-01-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_facebook_home_instagram_home_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is published?'),
        ),
    ]
