# Generated by Django 5.2.9 on 2026-01-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read?')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.TextField(verbose_name='Phone')),
                ('email', models.TextField(verbose_name='Email')),
                ('website', models.TextField(verbose_name='Website')),
                ('website_link', models.URLField(verbose_name='Website link')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published?')),
            ],
        ),
    ]
