# Generated by Django 5.2.9 on 2026-01-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_article_tags_articleblog_comment_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
    ]
