# Generated by Django 5.2.9 on 2026-01-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_comment_body_remove_comment_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published?'),
        ),
    ]
