# Generated by Django 5.2.9 on 2026-01-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_articleblog_title_alter_comment_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='how_it_works',
            field=models.TextField(default='', verbose_name='How it works'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArticleBlog',
        ),
    ]
