# Generated by Django 5.2.9 on 2026-01-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_article_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
