# Generated by Django 5.2.9 on 2026-01-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_comment_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('how_i_work', models.TextField(verbose_name='How I work')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published?')),
            ],
        ),
    ]
