# Generated by Django 5.2.9 on 2026-01-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.TextField(verbose_name='Phone')),
                ('telegram', models.URLField(verbose_name='Telegram')),
            ],
        ),
    ]
