# Generated by Django 5.2.9 on 2026-01-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is published?'),
        ),
    ]
