# Generated by Django 5.2.10 on 2026-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_footer_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='page_title',
            field=models.CharField(default='', max_length=50, verbose_name='Page title'),
            preserve_default=False,
        ),
    ]
